App:
  # 支持添加多个 Key
  GeminiKey:
    - YOUR-GEMINI-KEY
  GeminiUrl: https://generativelanguage.googleapis.com
  UserAgents:
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.2.15
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.66

# 本地服务启动配置项
Server:
  Port: 8080
  Host: localhost

# 代理配置(http|https|socks5://ip:port)，为空则不使用代理
Proxy:
  Protocol: